name: test
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 1.27.x
      - name: Run tests
        run: make test
      - name: Run linters
        run: make lint
      - name: Build binary
        run: make build
      - name: Build Docker image
        run: make docker-build
      - name: Check if working tree is dirty
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            git --no-pager diff
            echo 'run make test and commit changes'
            exit 1
          fi
